dhst/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('search/', include('search.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

search/urls.py
from django.urls import path

from . import views

app_name = 'search'

urlpatterns = [
    path('', views.index, name='index'),
]

search/models.py
from django.db import models

class Question(models.Model):
    question_stem = models.CharField(max_length=400)
    answer = models.ImageField()
    ori_path = models.CharField(max_length=200)

search/views.py
from django.shortcuts import render

from .models import Question

def index(request):
    try:
        search_result = Question.objects.filter(question_stem__contains=request.POST['query'])
        context={
            'search_result':search_result,
            'previous_query':request.POST['query'],
        }
        return render(request,'search/index.html',context)
    except:
        return render(request,'search/index.html')

search/templates/search/index.html
<!DOCTYPE html>
<html>
  <head>
    <title>大猴搜题</title>

    <!-- KaTeX module -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.css" integrity="sha384-zB1R0rpPzHqg7Kpt0Aljp8JPLqbXI3bhnPWROx27a9N0Ll6ZP/+DiW/UqRcLbRjq" crossorigin="anonymous">

    <!-- The loading of KaTeX is deferred to speed up page rendering -->
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.js" integrity="sha384-y23I5Q6l+B6vatafAwxRu/0oK/79VlbSz7Q9aiSZUvyWYIYsd+qj+o24G5ZU2zJz" crossorigin="anonymous"></script>

    <!-- To automatically render math in text elements, include the auto-render extension: -->
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/contrib/auto-render.min.js" integrity="sha384-kWPLUVMOks5AQFrykwIup5lo0m3iMkkHrD0uJ4H5cjeGihAutqP0yW0J6dpFiVkI" crossorigin="anonymous"
        onload="let textarea=document.getElementsByTagName('textarea')[0];
        let preview=document.getElementsByClassName('preview')[0];
        function renew(){
            preview.textContent='\\('+textarea.value+'\\)';
            renderMathInElement(preview,);
        }
        renew();
        renderMathInElement(document.body);
        textarea.addEventListener('input',renew)"></script>

  </head>

  <body>
    {% if search_result %}
        <p>以下可能是您想要找的题目：</p>
        <ul>
            {% for result in search_result %}
                <li>
                    <p class="stem">{{ result.question_stem }}</p>
                    <img src="../upload/{{ result.answer }}" width="760px" alt="{{ result.ori_path }}">
                </li>
            {% endfor %}
        </ul>
    {% elif previous_query %}
        <p>没有找到您查找的题目</p>
    {% endif %}

    <p class="preview"></p>

    <form action="{% url 'search:index' %}" method="POST">
        {% csrf_token %}
        <textarea name="query" id="query" cols="100" rows="5" placeholder="输入题目，公式使用TeX语法">{{ previous_query }}</textarea>
        <input type="submit" value="搜索">
    </form>

  </body>
</html>